server:
  port: 10000

management:
  server:
    port: 8081
  health:
    ping:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

detect_dne:
  serverMapping: server
  defaultStrategy: BruteForce
  seqData:
    fieldName: seq
    schema: |
      {
        "$schema": "https://json-schema.org/draft/2019-09/schema",
        "properties": {
          "seq": {
            "type": "array",
            "minItems": 3
          }
        },
        "required": ["seq"]
      }

