name: Bump version and release

on:
  push:
    branches:
      - 'main'

jobs:
  bump-version-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: bump-everywhere
      uses: undergroundwires/bump-everywhere@1.4.0
